### ISSUE TITLE
请问project的start code在哪获取

### ISSUE THREAD

**Issue by zgzaacm** [maksir98/cs61c#1]
rt

**Comment by maksir98** [comment]
[Project 1](https://github.com/61c-teach/su20-proj1-starter)
[Project 2](https://github.com/61c-teach/su20-proj2-starter)
[Project 3](https://github.com/61c-teach/su20-proj3-starter)
[Project 4](https://github.com/61c-teach/su20-proj4-starter)

另附[lab的start code地址](https://github.com/61c-teach/su20-lab-starter)
